/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectOperationBgPanel.java
 *
 * Created on Jun 9, 2011, 2:21:27 PM
 */
package com.mul.app.ui.bg;

import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Aity
 */
public class SelectOperationBgPanel extends javax.swing.JPanel {

    private Image image = null;

    /** Creates new form SelectOperationBgPanel */
    public SelectOperationBgPanel() {
        initComponents();
        try {
            //java.net.URL imgURL = getClass().getResource("icons/win_icon.gif");
            image = new ImageIcon(getClass().getResource("/com/mul/app/ui/bg/imgs/select_operation.png")).getImage();// ImageIO.read(new File("login-register1.png"));
            //image = ImageIO.read(new File(".\\src\\test\\jjjjj.GIF"))
            int d = 3;
        } catch (Exception e) {
            e.toString();
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (this.image != null) {

            g.draw3DRect(0, 0, this.getWidth(), this.getHeight(), true);
            g.drawImage(this.image, 0, 0, this.getWidth(), this.getHeight(), this);
            g.drawImage(this.image, 0, 0, this.getWidth(), this.getHeight(), this);
            //g.setPaint(red);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame("Testing");
                frame.setContentPane(new SelectOperationBgPanel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
