/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterPanel.java
 *
 * Created on Jun 7, 2011, 11:53:51 AM
 */
package com.mul.app.ui;

import com.mul.app.MainApp;
import com.mul.app.db.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import com.mul.app.audio.MidiPlayer;
/**
 *
 * @author Aity
 */
public class EnterPanel extends javax.swing.JPanel {

    /** Creates new form EnterPanel */
    public EnterPanel() {
        initComponents();
        doEnterListData();
        MidiPlayer.play("HeWillDoNewThings1.mid", true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEnterRegisterPanel1 = new com.mul.app.ui.bg.EnterRegisterBgPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userSelectList = new javax.swing.JList();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        userSelectList.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        userSelectList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        userSelectList.setToolTipText("<html><b>Select a user</b></html>");
        jScrollPane1.setViewportView(userSelectList);

        newButton.setText("NEW");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgEnterRegisterPanel1Layout = new javax.swing.GroupLayout(bgEnterRegisterPanel1);
        bgEnterRegisterPanel1.setLayout(bgEnterRegisterPanel1Layout);
        bgEnterRegisterPanel1Layout.setHorizontalGroup(
            bgEnterRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEnterRegisterPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEnterRegisterPanel1Layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEnterRegisterPanel1Layout.createSequentialGroup()
                .addContainerGap(739, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        bgEnterRegisterPanel1Layout.setVerticalGroup(
            bgEnterRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEnterRegisterPanel1Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(188, 188, 188)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgEnterRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(deleteButton)
                    .addComponent(okButton))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgEnterRegisterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgEnterRegisterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainApp.doExit();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        MainView.switchView(new RegisterPanel());
    }//GEN-LAST:event_newButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        MainView.currentUser = (String) userSelectList.getSelectedValue();
        if (MainView.currentUser == null) {
            JOptionPane.showMessageDialog(this, "You must select a user else add new user", "Error", 1, null);
            return;
        }
        MainView.switchView(new SelectOperationPanel());

    }//GEN-LAST:event_okButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        MainView.currentUser = (String) userSelectList.getSelectedValue();
        if (MainView.currentUser == null) {
            JOptionPane.showMessageDialog(this, "You must select a user to delete", "Error", 1, null);
            return;
        }
        doDeleteUser(MainView.currentUser);
        MainView.switchView(new EnterPanel());
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mul.app.ui.bg.EnterRegisterBgPanel bgEnterRegisterPanel1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton okButton;
    private javax.swing.JList userSelectList;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel examModelList;

    private void doEnterListData() {
        examModelList = new javax.swing.DefaultListModel();
        DBConnection dbcon = new DBConnection();
        dbcon.init("mulapp.db.aity", "", "");
        Connection conn = dbcon.getConnection();
        try {
            Statement s = conn.createStatement();
            ResultSet rsCSStuff = s.executeQuery("SELECT * FROM app_users");
            while (rsCSStuff.next()) {
                examModelList.addElement(rsCSStuff.getString("username"));
            }
            dbcon.close(rsCSStuff);
            dbcon.close(s);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        userSelectList.setModel(examModelList);
    }

    private void doDeleteUser(String username) {
        DBConnection dbcon = new DBConnection();
        dbcon.init("mulapp.db.aity", "", "");
        Connection conn = dbcon.getConnection();

        try {
            conn.setAutoCommit(false);
            Statement s = conn.createStatement();
            s.execute("DELETE FROM  app_users WHERE username = '" + username + "'");
            conn.commit();
            dbcon.close(s);
            dbcon.destroy();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error encountered on deleting", "Error", JOptionPane.ERROR, null);
            System.out.println(e.getMessage());
        }
    }
}
