/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainLesson.java
 *
 * Created on Jun 12, 2011, 1:07:01 PM
 */
package com.mul.app.ui;

import com.mul.app.MainApp;
import com.mul.app.ui.bg.ShowLessonImageBgPanel;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;
import com.mul.app.audio.MidiPlayer;
import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
/**
 *
 * @author Aity
 */
public class MainLesson extends javax.swing.JPanel {

    private int currentAlphabet = 1;
    private String currentAlphabetName = "Letter A stands for APPLE";
    private int currentDisplayTextIndex=0;
    ShowLessonImageBgPanel np;
    private ArrayList<String> list = new ArrayList<String>();
    private AudioClip audioClip;
    private ArrayList<String> audio = new ArrayList<String>();
    private URL urlForAudio;
    private int audioIndex=0;
    private Timer timer;

    /** Creates new form MainLesson */
    public MainLesson() {
        initComponents();
        listInitializer();
        audioInitializer();
        jTextField1.setEditable(false);
        jButton3.setEnabled(false);
        np = new ShowLessonImageBgPanel("A");
        hgujgjugju.removeAll();
        hgujgjugju.setLayout(new BorderLayout());
        hgujgjugju.add(np, BorderLayout.CENTER);
        hgujgjugju.validate();
        hgujgjugju.add(np);
        ShowLessonImageBgPanel.objLabel.setText(currentAlphabetName);
        jTextField1.setText(list.get(currentDisplayTextIndex));
        prevButton.setEnabled(false);
        np.start();
        MidiPlayer.stop();
        tune(audio.get(audioIndex));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLessonBgPanel = new com.mul.app.ui.bg.MainLessonBgPanel();
        hgujgjugju = new javax.swing.JPanel();
        nxtButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        hgujgjugju.setMaximumSize(new java.awt.Dimension(535, 302));
        hgujgjugju.setMinimumSize(new java.awt.Dimension(535, 302));

        javax.swing.GroupLayout hgujgjugjuLayout = new javax.swing.GroupLayout(hgujgjugju);
        hgujgjugju.setLayout(hgujgjugjuLayout);
        hgujgjugjuLayout.setHorizontalGroup(
            hgujgjugjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        hgujgjugjuLayout.setVerticalGroup(
            hgujgjugjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        nxtButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        nxtButton.setText("NEXT >>");
        nxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtButtonActionPerformed(evt);
            }
        });

        prevButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        prevButton.setText("<< PREVIOUS");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setText("HOME");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Click here for automatic scrolling");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Take Lesson Again");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLessonBgPanelLayout = new javax.swing.GroupLayout(mainLessonBgPanel);
        mainLessonBgPanel.setLayout(mainLessonBgPanelLayout);
        mainLessonBgPanelLayout.setHorizontalGroup(
            mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(hgujgjugju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                .addContainerGap(733, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                        .addComponent(prevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nxtButton)))
                .addGap(174, 174, 174))
        );
        mainLessonBgPanelLayout.setVerticalGroup(
            mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(hgujgjugju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nxtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainLessonBgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLessonBgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtButtonActionPerformed
        // TODO add your handling code here:
        stop();
        String nxtAlph = getNextAlphabet();
        switchAlphabet(nxtAlph);
        ShowLessonImageBgPanel.objLabel.setText(currentAlphabetName);
        jTextField1.setText(list.get(currentDisplayTextIndex));
        tune(audio.get(audioIndex));
    }//GEN-LAST:event_nxtButtonActionPerformed
  
    
    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        stop();
        String nxtAlph = getPrevAlphabet();
        switchAlphabet(nxtAlph);
        ShowLessonImageBgPanel.objLabel.setText(currentAlphabetName);
        jTextField1.setText(list.get(currentDisplayTextIndex));
        tune(audio.get(audioIndex));
        
        
    }//GEN-LAST:event_prevButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainView.switchView(new EnterPanel());
         stop();
         try{
          timer.stop();
         }
         catch(Exception e){}
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jButton2.setEnabled(false);
       timer = new Timer(10000, new TimerListener());
       timer.setInitialDelay(5000);
       timer.start();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainView.switchView(new MainLesson());
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hgujgjugju;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private com.mul.app.ui.bg.MainLessonBgPanel mainLessonBgPanel;
    private javax.swing.JButton nxtButton;
    private javax.swing.JButton prevButton;
    // End of variables declaration//GEN-END:variables


    private String getNextAlphabet() {
        if (currentAlphabet < 26) {
            currentDisplayTextIndex++;
            audioIndex++;
            currentAlphabet += 1;
            if (currentAlphabet == 26) {
                nxtButton.setEnabled(false);
                jButton3.setEnabled(true);
            } else {
                nxtButton.setEnabled(true);
                prevButton.setEnabled(true);
            }
            currentAlphabetName = MainApp.alphas.get(currentAlphabet);
             return  MainApp.alphas.get(currentAlphabet).substring(20, 21);
             
        } else {
            stop();
            timer.stop();
            currentAlphabetName = MainApp.alphas.get(currentAlphabet);
            return MainApp.alphas.get(currentAlphabet).substring(20, 21);
        }
    }

    private String getPrevAlphabet() {
        if (currentAlphabet > 1) {
            currentDisplayTextIndex--;
            audioIndex--;
            currentAlphabet -= 1;
            if (currentAlphabet == 1) {
                prevButton.setEnabled(false);
            } else {
                prevButton.setEnabled(true);
                nxtButton.setEnabled(true);
            }
            currentAlphabetName = MainApp.alphas.get(currentAlphabet);
            return MainApp.alphas.get(currentAlphabet).substring(20, 21);
        } else {
            currentAlphabetName = MainApp.alphas.get(currentAlphabet);
            return MainApp.alphas.get(currentAlphabet).substring(20, 21);
        }
    }

    private void switchAlphabet(String alphabet) {
        np.stop();
        np = new ShowLessonImageBgPanel(alphabet);
        hgujgjugju.removeAll();
        hgujgjugju.setLayout(new BorderLayout());
        hgujgjugju.add(np, BorderLayout.CENTER);
        hgujgjugju.validate();
        hgujgjugju.add(np);
        np.start();
        //this.mainPanel.repaint();
    }
     public void audioInitializer(){
     audio.add("AU/A.au");
     audio.add("AU/B.au");
     audio.add("AU/C.au");
     audio.add("AU/D.au");
     audio.add("AU/E.au");
     audio.add("AU/F.au");
     audio.add("AU/G.au");
     audio.add("AU/H.au");
     audio.add("AU/I.au");
     audio.add("AU/J.au");
     audio.add("AU/K.au");
     audio.add("AU/L.au");
     audio.add("AU/M.au");
     audio.add("AU/N.au");
     audio.add("AU/O.au");
     audio.add("AU/P.au");
     audio.add("AU/Q.au");
     audio.add("AU/R.au");
     audio.add("AU/S.au");
     audio.add("AU/T.au");
     audio.add("AU/U.au");
     audio.add("AU/V.au");
     audio.add("AU/W.au");
     audio.add("AU/X.au");
     audio.add("AU/Y.au");
     audio.add("AU/Z.au");
      }
     public void tune(String s){
          urlForAudio = getClass().getResource(s);
        audioClip = Applet.newAudioClip(urlForAudio);
        audioClip.play();
         }
     public void stop(){
         audioClip.stop();
     }
 public void listInitializer(){
     list.add("APPLE is good for eating");
     list.add("This is a BALL");
     list.add("My grandmother has a CAT");
     list.add("The DOG is barking");
     list.add("EGG is a source of protein");
     list.add("FISH lives in water");
     list.add("GOAT eats grass");
     list.add("My father has a HOUSE");
     list.add("The IRON is on the floor");
     list.add("The JUG contains water");
     list.add("The KEY is in my pocket");
     list.add("The LION is in the zoo");
     list.add("Simbi is sleeping on the MAT");
     list.add("The NAIL is sharp");
     list.add("I love ORANGES");
     list.add("The PENCIL is mine");
     list.add("The QUEEN is beautiful");
     list.add("My Sister hates RAT");
     list.add("The SNAIL has a  hard shell");
     list.add("The TABLE has four legs");
     list.add("The UMBRELLA is colourful");
     list.add("The VAN is coming");
     list.add("I have a WATCH");
     list.add("This is my XYLOPHONE");
     list.add("The YAM is in the kitchen");
     list.add("ZEBRA loves eating grass");
 }
 class TimerListener implements ActionListener {
      /** Handle ActionEvent */
       public void actionPerformed(ActionEvent e) {
           
         nxtButtonActionByTimer(e);
         
      }
 }
  private void nxtButtonActionByTimer(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       nxtButtonActionPerformed(evt);
       nxtButton.setEnabled(false);
       prevButton.setEnabled(false);

    }
}