/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on Jun 5, 2011, 5:49:26 PM
 */
package com.mul.app.ui;

import com.mul.app.MainApp;
import com.mul.app.ui.bg.MainBgPanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.DisplayMode;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 *
 * @author Aity
 */
public class MainView extends javax.swing.JFrame {

    NewJPanel np;
    private Toolkit toolkit;
    public static String currentUser;

    /** Creates new form MainView */
    public MainView() {
        np = new NewJPanel();
        try {
            SynthLookAndFeel synth = new SynthLookAndFeel();
            synth.load(SynthFrame.class.getResourceAsStream("easynth.xml"), SynthFrame.class);
            UIManager.setLookAndFeel(synth);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        appInit();
        //setSize(r.width + left + right, r.height + top + bottom);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bagroungPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bagroungPanelLayout = new javax.swing.GroupLayout(bagroungPanel);
        bagroungPanel.setLayout(bagroungPanelLayout);
        bagroungPanelLayout.setHorizontalGroup(
            bagroungPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(bagroungPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bagroungPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bagroungPanelLayout.setVerticalGroup(
            bagroungPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(bagroungPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bagroungPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(bagroungPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        this.np.setSize(evt.getComponent().getSize());
        this.resize(this.np);
        this.repaint();
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MainView().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bagroungPanel;
    private static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public static void switchView(JPanel newView) {
        mainPanel.removeAll();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(newView, BorderLayout.CENTER);
        mainPanel.validate();
        //this.mainPanel.repaint();
    }

    private void appInit() {
        //this.setUndecorated(true);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsConfiguration gc = getGraphicsConfiguration();
        GraphicsDevice gd;
        gd = ge.getDefaultScreenDevice();
        toolkit = Toolkit.getDefaultToolkit();
        int bottom = toolkit.getScreenInsets(gc).bottom;
        int top = toolkit.getScreenInsets(gc).top;
        int left = toolkit.getScreenInsets(gc).left;
        int right = toolkit.getScreenInsets(gc).right;
        Rectangle r = ge.getMaximumWindowBounds();
        DisplayMode newDisplayMode = new DisplayMode(r.width + left + right, r.height + top + bottom, 32, 0);
        if (gd.isFullScreenSupported()) {
            gd.setFullScreenWindow(this);
        } else {
            ;//
            System.exit(0);
        }

        if (gd.isDisplayChangeSupported()) {
            gd.setDisplayMode(newDisplayMode);
        } else {
            ;//
            System.exit(0);
        }
        MainApp.loadAlphabets();
        this.switchView(new EnterPanel());
    }

    private void resize(Component c) {
        this.getContentPane().remove(this.np);
        this.bagroungPanel.add(np);
    }
}
