/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainLesson.java
 *
 * Created on Jun 12, 2011, 1:07:01 PM
 */
package com.mul.app.ui;

import com.mul.app.MainApp;
import com.mul.app.Rounder;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Aity
 */
public class MainGame extends javax.swing.JPanel {

    protected int range = 1;
    protected String tempStr[] = null;
    protected GamePanel demo;
    protected String randAlp[];
    protected Thread threadAnim;
    protected int numberGotten = 0;

    /** Creates new form MainLesson */
    public MainGame() {
        examModelList = new javax.swing.DefaultListModel();
        threadAnim = new Thread();
        initComponents();
        jList1.setModel(examModelList);
        jSpinner1.setModel(timerListModel);
        randAlp = new String[26];
        randAlphabet();
        tempStr = new String[6];
        for (int i = 0; i < 6; i++) {
            tempStr[i] = randAlp[i];
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispMsgPanel = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        mainLessonBgPanel = new com.mul.app.ui.bg.MainLessonBgPanel();
        resultTextField = new javax.swing.JTextField();
        displayAnimPanel = new javax.swing.JPanel();
        dispGameInfoPanel = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gameStartBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        dispMsgPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 58));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("End of Little Game");

        scoreLabel.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 48));
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dispMsgPanelLayout = new javax.swing.GroupLayout(dispMsgPanel);
        dispMsgPanel.setLayout(dispMsgPanelLayout);
        dispMsgPanelLayout.setHorizontalGroup(
            dispMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addComponent(scoreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        dispMsgPanelLayout.setVerticalGroup(
            dispMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dispMsgPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        resultTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultTextField.setForeground(new java.awt.Color(102, 102, 0));
        resultTextField.setBorder(null);
        resultTextField.setOpaque(false);
        resultTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultTextFieldKeyReleased(evt);
            }
        });

        displayAnimPanel.setBackground(new java.awt.Color(0, 0, 0));
        displayAnimPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(51, 51, 51))));
        displayAnimPanel.setMaximumSize(new java.awt.Dimension(535, 302));
        displayAnimPanel.setMinimumSize(new java.awt.Dimension(535, 302));
        displayAnimPanel.setPreferredSize(new java.awt.Dimension(535, 302));

        dispGameInfoPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 68));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ABOUT TO START LITTLE GAME");

        jSpinner1.setFont(new java.awt.Font("Agency FB", 1, 48));
        jSpinner1.setValue(120);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 30));
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Enter Duration in Min(s)");

        javax.swing.GroupLayout dispGameInfoPanelLayout = new javax.swing.GroupLayout(dispGameInfoPanel);
        dispGameInfoPanel.setLayout(dispGameInfoPanelLayout);
        dispGameInfoPanelLayout.setHorizontalGroup(
            dispGameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dispGameInfoPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        dispGameInfoPanelLayout.setVerticalGroup(
            dispGameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dispGameInfoPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dispGameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout displayAnimPanelLayout = new javax.swing.GroupLayout(displayAnimPanel);
        displayAnimPanel.setLayout(displayAnimPanelLayout);
        displayAnimPanelLayout.setHorizontalGroup(
            displayAnimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dispGameInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        displayAnimPanelLayout.setVerticalGroup(
            displayAnimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dispGameInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setText("HOME");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gameStartBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        gameStartBtn.setText("CLICK TO START");
        gameStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStartBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mul/app/ui/images/xmarks.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainLessonBgPanelLayout = new javax.swing.GroupLayout(mainLessonBgPanel);
        mainLessonBgPanel.setLayout(mainLessonBgPanelLayout);
        mainLessonBgPanelLayout.setHorizontalGroup(
            mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                        .addComponent(displayAnimPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLessonBgPanelLayout.createSequentialGroup()
                                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                                .addComponent(gameStartBtn)
                                .addGap(338, 338, 338))))))
        );
        mainLessonBgPanelLayout.setVerticalGroup(
            mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayAnimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLessonBgPanelLayout.createSequentialGroup()
                        .addGroup(mainLessonBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addComponent(gameStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(268, 268, 268))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainLessonBgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLessonBgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gameStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStartBtnActionPerformed
        // TODO add your handling code here:
        demo = new GamePanel(tempStr, 6);
        displayAnimPanel.removeAll();
        displayAnimPanel.setLayout(new BorderLayout());
        displayAnimPanel.add(demo, BorderLayout.CENTER);
        displayAnimPanel.validate();
        displayAnimPanel.add(demo);
        demo.start();
        nextSet();
        gameCount((Integer) jSpinner1.getValue());
        gameStartBtn.setEnabled(false);
    }//GEN-LAST:event_gameStartBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainView.switchView(new EnterPanel());
}//GEN-LAST:event_jButton1ActionPerformed

    private void resultTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultTextFieldKeyReleased
        // TODO add your handling code here:
        CheckSpellImage();
    }//GEN-LAST:event_resultTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel dispGameInfoPanel;
    private java.awt.Panel dispMsgPanel;
    private javax.swing.JPanel displayAnimPanel;
    private javax.swing.JButton gameStartBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private com.mul.app.ui.bg.MainLessonBgPanel mainLessonBgPanel;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
    protected javax.swing.DefaultListModel examModelList;
    protected SpinnerModel timerListModel = new SpinnerNumberModel(100, 20, 200, 1);

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void randAlphabet() {
        for (int i = 0; i < 26; i++) {
            randAlp[i] = MainApp.alphas.get(i + 1).substring(20, 21) + ".png";
        }
        shuffle(randAlp);
    }

    // swaps array elements i and j
    public static void exch(String[] a, int i, int j) {
        String swap = a[i];
        a[i] = a[j];
        a[j] = swap;
    }

    // take as input an array of strings and rearrange them in random order
    public static void shuffle(String[] a) {
        int N = a.length;
        for (int i = 0; i < N; i++) {
            int r = i + (int) (Math.random() * (N - i));   // between i and N-1
            exch(a, i, r);
        }
    }

    // take as input an array of strings and print them out to standard output
    public static void show(String[] a) {
        for (int i = 0; i < a.length; i++) {
            System.out.println(a[i]);
        }
    }

    private void CheckSpellImage() {
        for (int i = 0; i < tempStr.length; i++) {
            String tempAlpha = MainApp.alphas2.get(tempStr[i].substring(0, 1));
            if (resultTextField.getText().trim().equalsIgnoreCase(tempAlpha)) {
                if (!examModelList.contains(tempAlpha)) {
                    examModelList.addElement(tempAlpha);
                    numberGotten++;
                    animClearText();
                }
            }
            if (tempStr.length == examModelList.size() && tempStr.length != 8) {
                JOptionPane.showMessageDialog(this, "Move to next group", "Correct", 1, null);
                examModelList.clear();
                nextSet();
                return;
            } else if (tempStr.length == examModelList.size() && tempStr.length == 8) {
                JOptionPane.showMessageDialog(this, "Thanks, this is the last", "Final Stage", 1, null);
                examModelList.clear();
                return;
            }
        }

    }

    protected void nextSet() {
        demo.stop();
        int show = 6;
        if (range == 1) {
            tempStr = new String[show];
            int j = 0;
            for (int i = 0; i < 6; i++) {
                tempStr[j] = randAlp[i];
                j += 1;
            }
            range = 2;
        } else if (range == 2) {
            tempStr = new String[show];
            int j = 0;
            for (int i = 6; i < 12; i++) {
                tempStr[j] = randAlp[i];
                j += 1;
            }
            range = 3;
        } else if (range == 3) {
            tempStr = new String[show];
            int j = 0;
            for (int i = 12; i < 18; i++) {
                tempStr[j] = randAlp[i];
                j += 1;
            }
            range = 4;
        } else if (range == 4) {
            show = 8;
            tempStr = new String[show];
            int j = 0;
            for (int i = 18; i < 26; i++) {
                tempStr[j] = randAlp[i];
                j += 1;
            }
        }

        demo = new GamePanel(tempStr, show);
        displayAnimPanel.removeAll();
        displayAnimPanel.setLayout(new BorderLayout());
        displayAnimPanel.add(demo, BorderLayout.CENTER);
        displayAnimPanel.validate();
        displayAnimPanel.add(demo);
        demo.start();
    }

    protected void animClearText() {
        if (threadAnim.isAlive()) {
            threadAnim = null;
        }
        threadAnim = new Thread() {

            @Override
            public void run() {
                try {
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mul/app/ui/images/mark.png"))); // NOI18N
                    Thread.sleep(1500);
                } catch (Exception e) {
                }
                int len = resultTextField.getText().length();


                for (int i = 0; i < len; i++) {
                    try {
                        Thread.sleep(200);
                        resultTextField.setText(resultTextField.getText().substring(0, len - 1 - i));
                    } catch (Exception e) {
                    }
                }
                String correct = "Enter the next Object";
                int correctLen = correct.length();
                for (int i = 0; i < correctLen; i++) {
                    try {
                        Thread.sleep(100);
                        resultTextField.setText(correct.substring(0, i + 1));
                    } catch (Exception e) {
                    }
                }
                try {
                    Thread.sleep(1100);
                } catch (Exception e) {
                }
                jLabel3.setIcon(null);
                resultTextField.setText("");
            }
        };
        threadAnim.start();
    }

    protected void gameCount(final int time) {

        Thread thread = new Thread() {

            @Override
            public void run() {
                for (int i = 0; i <= time; i++) {
                    try {
                        jLabel2.setText(String.valueOf(time - i));
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }

                }
                float score = (numberGotten / 26.00f);
                score = score * 100;
                score = Rounder.round(score, 2);
                scoreLabel.setText("Hi " + MainView.currentUser + " You Scored " + score + "%");
                displayAnimPanel.removeAll();
                displayAnimPanel.setLayout(new BorderLayout());
                displayAnimPanel.add(dispMsgPanel, BorderLayout.CENTER);
                displayAnimPanel.validate();
            }
        };
        thread.start();
    }
}
